# Generated by Django 5.2.4 on 2025-08-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='converted_video_file',
            field=models.FileField(blank=True, null=True, upload_to='clips/converted'),
        ),
        migrations.AlterField(
            model_name='clip',
            name='video_file',
            field=models.FileField(upload_to='clips/raw_uploads'),
        ),
    ]
